services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env.production
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    restart: always
    container_name: MySQL_API_Container
    environment:
      MYSQL_ROOT_PASSWORD: Caderno@2
      MYSQL_DATABASE: residencia00003
      MYSQL_USER: testUser 
      MYSQL_PASSWORD: cad@45
    ports:
      - "3307:3306"  # corrigido para mapear porta correta
    volumes:
      - ./database/residencia00003.sql:/docker-entrypoint-initdb.d/residencia00003.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
