version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RecipePassword
      MYSQL_DATABASE: bonsaeSQL
      MYSQL_USER: admin
      MYSQL_PASSWORD: bonsae123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3307:3306'  

volumes:
  mysql_data:

