services:
  backend:
    build:
      context: .
      dockerfile: DockerFile.backend
    env_file: 
      - .env.production
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app_network
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: testUser
      DB_PASS: cad@45
      DB_NAME: residencia00003

  frontend:
    build:
      context: .
      dockerfile: DockerFile.frontend
    ports:
      - "3000:3000" 
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
      - NPM_CONFIG_OPTIONAL=true
    networks:
      - app_network



  mysql:
    image: mysql:5.7
    restart: always
    container_name: MySQL_API_Container
    environment:
      MYSQL_ROOT_PASSWORD: Caderno@2
      MYSQL_DATABASE: residencia00003
      MYSQL_USER: testUser 
      MYSQL_PASSWORD: cad@45
    ports:
      - "3307:3306"  # corrigido para mapear porta correta
    volumes:
      - ./database/residencia00003.sql:/docker-entrypoint-initdb.d/residencia00003.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
